// 农夫乐事 · 合成表数据
// 配方来源：CE 内容包 recipes.yml（v0.10.7）；贴图：FD 物品取自 public/farming，原版物品取自 public/farming/item/vanilla。

export type RecipeType = 'crafting' | 'smelting' | 'smoking' | 'campfire' | 'smithing'

export interface ItemInfo { name: string; texture: string }

export interface CraftingRecipe {
  id: string
  name: string
  result: string
  count: number
  type: RecipeType
  grid: (string | null)[]
  station: string
  shapeless?: boolean
}

export const ITEMS: Record<string, ItemInfo> = {
  "#minecraft:planks": { name: "\u4efb\u610f\u6728\u677f", texture: "/farming/item/vanilla/oak_planks.png" },
  "farmersdelight:apple_pie": { name: "\u82f9\u679c\u6d3e", texture: "/farming/item/apple_pie.png" },
  "farmersdelight:bacon": { name: "\u751f\u57f9\u6839", texture: "/farming/item/bacon.png" },
  "farmersdelight:bacon_sandwich": { name: "\u57f9\u6839\u4e09\u660e\u6cbb", texture: "/farming/item/bacon_sandwich.png" },
  "farmersdelight:beef_patty": { name: "\u725b\u8089\u997c", texture: "/farming/item/beef_patty.png" },
  "farmersdelight:cabbage": { name: "\u5377\u5fc3\u83dc", texture: "/farming/item/cabbage.png" },
  "farmersdelight:canvas": { name: "\u7c97\u5e03", texture: "/farming/item/canvas.png" },
  "farmersdelight:chicken_sandwich": { name: "\u9e21\u8089\u4e09\u660e\u6cbb", texture: "/farming/item/chicken_sandwich.png" },
  "farmersdelight:cooked_bacon": { name: "\u719f\u57f9\u6839", texture: "/farming/item/cooked_bacon.png" },
  "farmersdelight:cooked_rice": { name: "\u7c73\u996d", texture: "/farming/item/cooked_rice.png" },
  "farmersdelight:cooking_pot": { name: "\u53a8\u9505", texture: "/farming/item/cooking_pot.png" },
  "farmersdelight:copper_knife": { name: "\u94dc\u5200", texture: "/farming/item/copper_knife.png" },
  "farmersdelight:cutting_board": { name: "\u7827\u677f", texture: "/farming/block/cutting_board.png" },
  "farmersdelight:diamond_knife": { name: "\u94bb\u77f3\u5200", texture: "/farming/item/diamond_knife.png" },
  "farmersdelight:egg_sandwich": { name: "\u5939\u86cb\u4e09\u660e\u6cbb", texture: "/farming/item/egg_sandwich.png" },
  "farmersdelight:flint_knife": { name: "\u71e7\u77f3\u5200", texture: "/farming/item/flint_knife.png" },
  "farmersdelight:fried_egg": { name: "\u714e\u86cb", texture: "/farming/item/fried_egg.png" },
  "farmersdelight:fruit_salad": { name: "\u6c34\u679c\u6c99\u62c9", texture: "/farming/item/fruit_salad.png" },
  "farmersdelight:golden_knife": { name: "\u91d1\u5200", texture: "/farming/item/golden_knife.png" },
  "farmersdelight:hamburger": { name: "\u6c49\u5821\u5305", texture: "/farming/item/hamburger.png" },
  "farmersdelight:iron_knife": { name: "\u94c1\u5200", texture: "/farming/item/iron_knife.png" },
  "farmersdelight:kelp_roll": { name: "\u6d77\u5e26\u5bff\u53f8\u5377", texture: "/farming/item/kelp_roll.png" },
  "farmersdelight:melon_juice": { name: "\u897f\u74dc\u6c41", texture: "/farming/item/melon_juice.png" },
  "farmersdelight:milk_bottle": { name: "\u5976\u74f6", texture: "/farming/item/milk_bottle.png" },
  "farmersdelight:minced_beef": { name: "\u725b\u8089\u9985", texture: "/farming/item/minced_beef.png" },
  "farmersdelight:mixed_salad": { name: "\u6df7\u5408\u6c99\u62c9", texture: "/farming/item/mixed_salad.png" },
  "farmersdelight:mushroom_rice": { name: "\u8611\u83c7\u996d", texture: "/farming/item/mushroom_rice.png" },
  "farmersdelight:netherite_knife": { name: "\u4e0b\u754c\u5408\u91d1\u5200", texture: "/farming/item/netherite_knife.png" },
  "farmersdelight:onion": { name: "\u6d0b\u8471", texture: "/farming/item/onion.png" },
  "farmersdelight:organic_compost": { name: "\u6709\u673a\u5806\u80a5", texture: "/farming/block/organic_compost_stage3.png" },
  "farmersdelight:pie_crust": { name: "\u9985\u997c\u9165\u76ae", texture: "/farming/item/pie_crust.png" },
  "farmersdelight:pumpkin_slice": { name: "\u5357\u74dc\u7247", texture: "/farming/item/pumpkin_slice.png" },
  "farmersdelight:rope": { name: "\u7ef3\u5b50", texture: "/farming/item/rope.png" },
  "farmersdelight:skillet": { name: "\u714e\u9505", texture: "/farming/block/skillet_top.png" },
  "farmersdelight:stove": { name: "\u7089\u7076", texture: "/farming/block/stove_front.png" },
  "farmersdelight:straw": { name: "\u8349\u79c6", texture: "/farming/item/straw.png" },
  "farmersdelight:stuffed_potato": { name: "\u586b\u9985\u9a6c\u94c3\u85af", texture: "/farming/item/stuffed_potato.png" },
  "farmersdelight:sweet_berry_cookie": { name: "\u751c\u6d46\u679c\u66f2\u5947", texture: "/farming/item/sweet_berry_cookie.png" },
  "farmersdelight:tomato": { name: "\u756a\u8304", texture: "/farming/item/tomato.png" },
  "farmersdelight:tomato_crate": { name: "\u7bb1\u88c5\u756a\u8304", texture: "/farming/block/tomato_crate_side.png" },
  "farmersdelight:wheat_dough": { name: "\u9762\u56e2", texture: "/farming/item/wheat_dough.png" },
  "minecraft:apple": { name: "\u82f9\u679c", texture: "/farming/item/vanilla/apple.png" },
  "minecraft:baked_potato": { name: "\u70e4\u9a6c\u94c3\u85af", texture: "/farming/item/vanilla/baked_potato.png" },
  "minecraft:beetroot": { name: "\u751c\u83dc\u6839", texture: "/farming/item/vanilla/beetroot.png" },
  "minecraft:bone_meal": { name: "\u9aa8\u7c89", texture: "/farming/item/vanilla/bone_meal.png" },
  "minecraft:bowl": { name: "\u7897", texture: "/farming/item/vanilla/bowl.png" },
  "minecraft:bread": { name: "\u9762\u5305", texture: "/farming/item/vanilla/bread.png" },
  "minecraft:brick": { name: "\u7816", texture: "/farming/item/vanilla/brick.png" },
  "minecraft:campfire": { name: "\u8425\u706b", texture: "/farming/item/vanilla/campfire.png" },
  "minecraft:carrot": { name: "\u80e1\u841d\u535c", texture: "/farming/item/vanilla/carrot.png" },
  "minecraft:cooked_beef": { name: "\u719f\u725b\u8089", texture: "/farming/item/vanilla/cooked_beef.png" },
  "minecraft:cooked_chicken": { name: "\u719f\u9e21\u8089", texture: "/farming/item/vanilla/cooked_chicken.png" },
  "minecraft:copper_ingot": { name: "\u94dc\u952d", texture: "/farming/item/vanilla/copper_ingot.png" },
  "minecraft:diamond": { name: "\u94bb\u77f3", texture: "/farming/item/vanilla/diamond.png" },
  "minecraft:dirt": { name: "\u6ce5\u571f", texture: "/farming/item/vanilla/dirt.png" },
  "minecraft:dried_kelp": { name: "\u5e72\u6d77\u5e26", texture: "/farming/item/vanilla/dried_kelp.png" },
  "minecraft:egg": { name: "\u9e21\u86cb", texture: "/farming/item/vanilla/egg.png" },
  "minecraft:flint": { name: "\u71e7\u77f3", texture: "/farming/item/vanilla/flint.png" },
  "minecraft:glass_bottle": { name: "\u73bb\u7483\u74f6", texture: "/farming/item/vanilla/glass_bottle.png" },
  "minecraft:gold_ingot": { name: "\u91d1\u952d", texture: "/farming/item/vanilla/gold_ingot.png" },
  "minecraft:iron_ingot": { name: "\u94c1\u952d", texture: "/farming/item/vanilla/iron_ingot.png" },
  "minecraft:melon_slice": { name: "\u897f\u74dc\u7247", texture: "/farming/item/vanilla/melon_slice.png" },
  "minecraft:netherite_ingot": { name: "\u4e0b\u754c\u5408\u91d1\u952d", texture: "/farming/item/vanilla/netherite_ingot.png" },
  "minecraft:netherite_upgrade_smithing_template": { name: "\u4e0b\u754c\u5408\u91d1\u5347\u7ea7\u6a21\u677f", texture: "/farming/item/vanilla/netherite_upgrade_smithing_template.png" },
  "minecraft:rotten_flesh": { name: "\u8150\u8089", texture: "/farming/item/vanilla/rotten_flesh.png" },
  "minecraft:stick": { name: "\u6728\u68cd", texture: "/farming/item/vanilla/stick.png" },
  "minecraft:sugar": { name: "\u7cd6", texture: "/farming/item/vanilla/sugar.png" },
  "minecraft:sweet_berries": { name: "\u751c\u6d46\u679c", texture: "/farming/item/vanilla/sweet_berries.png" },
  "minecraft:water_bucket": { name: "\u6c34\u6876", texture: "/farming/item/vanilla/water_bucket.png" },
  "minecraft:wheat": { name: "\u5c0f\u9ea6", texture: "/farming/item/vanilla/wheat.png" },
  "minecraft:wooden_shovel": { name: "\u6728\u94f2", texture: "/farming/item/vanilla/wooden_shovel.png" },
}

export const RECIPES: CraftingRecipe[] = [
  {
    id: "farmersdelight:cooking_pot",
    name: "\u53a8\u9505",
    result: "farmersdelight:cooking_pot",
    count: 1,
    type: "crafting",
    grid: ["minecraft:brick", "minecraft:wooden_shovel", "minecraft:brick", "minecraft:iron_ingot", "minecraft:water_bucket", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_ingot"],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:cutting_board",
    name: "\u7827\u677f",
    result: "farmersdelight:cutting_board",
    count: 1,
    type: "crafting",
    grid: ["minecraft:stick", "#minecraft:planks", "#minecraft:planks", "minecraft:stick", "#minecraft:planks", "#minecraft:planks", null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:skillet",
    name: "\u714e\u9505",
    result: "farmersdelight:skillet",
    count: 1,
    type: "crafting",
    grid: [null, "minecraft:iron_ingot", "minecraft:iron_ingot", null, "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:brick", null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:stove",
    name: "\u7089\u7076",
    result: "farmersdelight:stove",
    count: 1,
    type: "crafting",
    grid: ["minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:iron_ingot", "minecraft:brick", null, "minecraft:brick", "minecraft:brick", "minecraft:campfire", "minecraft:brick"],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:flint_knife",
    name: "\u71e7\u77f3\u5200",
    result: "farmersdelight:flint_knife",
    count: 1,
    type: "crafting",
    grid: ["minecraft:flint", "minecraft:stick", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:copper_knife",
    name: "\u94dc\u5200",
    result: "farmersdelight:copper_knife",
    count: 1,
    type: "crafting",
    grid: ["minecraft:copper_ingot", "minecraft:stick", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:iron_knife",
    name: "\u94c1\u5200",
    result: "farmersdelight:iron_knife",
    count: 1,
    type: "crafting",
    grid: ["minecraft:iron_ingot", "minecraft:stick", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:golden_knife",
    name: "\u91d1\u5200",
    result: "farmersdelight:golden_knife",
    count: 1,
    type: "crafting",
    grid: ["minecraft:gold_ingot", "minecraft:stick", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:diamond_knife",
    name: "\u94bb\u77f3\u5200",
    result: "farmersdelight:diamond_knife",
    count: 1,
    type: "crafting",
    grid: ["minecraft:diamond", "minecraft:stick", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:netherite_knife",
    name: "\u4e0b\u754c\u5408\u91d1\u5200",
    result: "farmersdelight:netherite_knife",
    count: 1,
    type: "smithing",
    grid: ["minecraft:netherite_upgrade_smithing_template", "farmersdelight:diamond_knife", "minecraft:netherite_ingot"],
    station: "\u953b\u9020\u53f0",
  },
  {
    id: "farmersdelight:organic_compost",
    name: "\u6709\u673a\u5806\u80a5",
    result: "farmersdelight:organic_compost",
    count: 1,
    type: "crafting",
    grid: ["minecraft:dirt", "minecraft:rotten_flesh", "minecraft:rotten_flesh", "farmersdelight:straw", "farmersdelight:straw", "minecraft:bone_meal", "minecraft:bone_meal", "minecraft:bone_meal", "minecraft:bone_meal"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:wheat_dough",
    name: "\u9762\u56e2",
    result: "farmersdelight:wheat_dough",
    count: 3,
    type: "crafting",
    grid: ["minecraft:wheat", "minecraft:wheat", "minecraft:wheat", "minecraft:egg"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:pie_crust",
    name: "\u9985\u997c\u9165\u76ae",
    result: "farmersdelight:pie_crust",
    count: 1,
    type: "crafting",
    grid: ["minecraft:wheat", "farmersdelight:milk_bottle", "minecraft:wheat", null, "minecraft:wheat", null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:fried_egg",
    name: "\u714e\u86cb",
    result: "farmersdelight:fried_egg",
    count: 1,
    type: "smelting",
    grid: ["minecraft:egg"],
    station: "\u7194\u7089",
  },
  {
    id: "farmersdelight:cooked_bacon",
    name: "\u719f\u57f9\u6839",
    result: "farmersdelight:cooked_bacon",
    count: 1,
    type: "smelting",
    grid: ["farmersdelight:bacon"],
    station: "\u7194\u7089",
  },
  {
    id: "farmersdelight:beef_patty",
    name: "\u725b\u8089\u997c",
    result: "farmersdelight:beef_patty",
    count: 1,
    type: "campfire",
    grid: ["farmersdelight:minced_beef"],
    station: "\u8425\u706b",
  },
  {
    id: "farmersdelight:hamburger",
    name: "\u6c49\u5821\u5305",
    result: "farmersdelight:hamburger",
    count: 1,
    type: "crafting",
    grid: ["minecraft:bread", "farmersdelight:beef_patty", "farmersdelight:cabbage", "farmersdelight:tomato", "farmersdelight:onion"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:bacon_sandwich",
    name: "\u57f9\u6839\u4e09\u660e\u6cbb",
    result: "farmersdelight:bacon_sandwich",
    count: 1,
    type: "crafting",
    grid: ["minecraft:bread", "farmersdelight:cooked_bacon", "farmersdelight:cabbage", "farmersdelight:tomato"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:egg_sandwich",
    name: "\u5939\u86cb\u4e09\u660e\u6cbb",
    result: "farmersdelight:egg_sandwich",
    count: 1,
    type: "crafting",
    grid: ["minecraft:bread", "farmersdelight:fried_egg", "farmersdelight:fried_egg"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:mixed_salad",
    name: "\u6df7\u5408\u6c99\u62c9",
    result: "farmersdelight:mixed_salad",
    count: 1,
    type: "crafting",
    grid: ["farmersdelight:cabbage", "farmersdelight:tomato", "minecraft:beetroot", "minecraft:bowl"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:fruit_salad",
    name: "\u6c34\u679c\u6c99\u62c9",
    result: "farmersdelight:fruit_salad",
    count: 1,
    type: "crafting",
    grid: ["minecraft:apple", "minecraft:melon_slice", "minecraft:melon_slice", "minecraft:sweet_berries", "minecraft:sweet_berries", "farmersdelight:pumpkin_slice", "minecraft:bowl"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:melon_juice",
    name: "\u897f\u74dc\u6c41",
    result: "farmersdelight:melon_juice",
    count: 1,
    type: "crafting",
    grid: ["minecraft:melon_slice", "minecraft:melon_slice", "minecraft:melon_slice", "minecraft:melon_slice", "minecraft:sugar", "minecraft:glass_bottle"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:sweet_berry_cookie",
    name: "\u751c\u6d46\u679c\u66f2\u5947",
    result: "farmersdelight:sweet_berry_cookie",
    count: 8,
    type: "crafting",
    grid: ["minecraft:sweet_berries", "minecraft:wheat", "minecraft:wheat"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:apple_pie",
    name: "\u82f9\u679c\u6d3e",
    result: "farmersdelight:apple_pie",
    count: 1,
    type: "crafting",
    grid: ["minecraft:wheat", "minecraft:wheat", "minecraft:wheat", "minecraft:apple", "minecraft:apple", "minecraft:apple", "minecraft:sugar", "farmersdelight:pie_crust", "minecraft:sugar"],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:kelp_roll",
    name: "\u6d77\u5e26\u5bff\u53f8\u5377",
    result: "farmersdelight:kelp_roll",
    count: 1,
    type: "crafting",
    grid: ["farmersdelight:cooked_rice", "minecraft:carrot", "farmersdelight:cooked_rice", "minecraft:dried_kelp", "minecraft:dried_kelp", "minecraft:dried_kelp", null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:stuffed_potato",
    name: "\u586b\u9985\u9a6c\u94c3\u85af",
    result: "farmersdelight:stuffed_potato",
    count: 1,
    type: "crafting",
    grid: ["minecraft:baked_potato", "minecraft:cooked_beef", "farmersdelight:milk_bottle"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:chicken_sandwich",
    name: "\u9e21\u8089\u4e09\u660e\u6cbb",
    result: "farmersdelight:chicken_sandwich",
    count: 1,
    type: "crafting",
    grid: ["minecraft:bread", "minecraft:cooked_chicken", "farmersdelight:cabbage", "minecraft:carrot"],
    station: "\u5de5\u4f5c\u53f0", shapeless: true,
  },
  {
    id: "farmersdelight:canvas",
    name: "\u7c97\u5e03",
    result: "farmersdelight:canvas",
    count: 1,
    type: "crafting",
    grid: ["farmersdelight:straw", "farmersdelight:straw", "farmersdelight:straw", "farmersdelight:straw", null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:rope",
    name: "\u7ef3\u5b50",
    result: "farmersdelight:rope",
    count: 4,
    type: "crafting",
    grid: ["farmersdelight:straw", "farmersdelight:straw", null, null, null, null, null, null, null],
    station: "\u5de5\u4f5c\u53f0",
  },
  {
    id: "farmersdelight:tomato_crate",
    name: "\u7bb1\u88c5\u756a\u8304",
    result: "farmersdelight:tomato_crate",
    count: 1,
    type: "crafting",
    grid: ["farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato", "farmersdelight:tomato"],
    station: "\u5de5\u4f5c\u53f0",
  },
]
